// constants

const constants = {
  GET_DECKS: "GET_DECKS",
  LOAD_DECKS: "LOAD_DECKS",
  GET_DECK: "GET_DECK",
  ADD_DECK: "ADD_DECK",
  DELETE_DECK: "DELETE_DECK",

  GET_CARD: "GET_CARD",
  ADD_CARD: "ADD_CARD",

  GET_QUIZ_PARAMETERS: "GET_QUIZ_PARAMETERS",
  SET_QUIZ_DECK: "SET_QUIZ_DECK",
  INCREMENT_SCORE: "INCREMENT_SCORE",
  DECREMENT_SCORE: "DECREMENT_SCORE",
  SET_SCORE: "SET_SCORE",
  SET_ACTIVE_QUESTION: "SET_ACTIVE_QUESTION",
  SET_SHOW_ANSWER: "SET_SHOW_ANSWER",
  SET_FINISHED: "SET_FINISHED",

  UDACICARDS_STORAGE_KEY: 'Udacicards_flashcards_key'
}

export default constants